name: CI Pipeline 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run basic smoke step
        run: |
          echo "Smoke check: Python and deps installed"
          python --version

      - name: Run tests
        run: |
         python -m pytest -q

      - name: Install Semgrep
        run: |
         pip install semgrep

      - name: Run Semgrep SAST
        run: |
         semgrep --config p/ci  

      - name: Run Semgrep SAST and save report
        run: |
         semgrep --config p/ci --json > semgrep_report.json
   
      - name: Start Flask service
        run: |
         nohup python app.py &
         sleep 5  
      - name: Run DAST with OWASP ZAP
        run: |
          docker run --network="host" \
            -v ${{ github.workspace }}:/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
              -t http://127.0.0.1:5000 \
              -r zap_report.html \
              -j zap_report.json || true

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-reports
          path: |
            zap_report.html
            zap_report.json

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t "${{ secrets.DOCKER_USERNAME }}/devops-mini-service:latest" .

      - name: Push Docker image
        run: |
          echo "Pushing Docker image..."
          docker push "${{ secrets.DOCKER_USERNAME }}/devops-mini-service:latest"

  deploy-k8s:
    runs-on: ubuntu-latest
    needs: build-test       
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kind
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/

      - name: Create kind cluster
        run: |
          kind create cluster --name ci-cluster

      - name: Apply k8s manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Wait for pod
        run: |
          kubectl wait --for=condition=available deployment/devops-mini-deployment --timeout=120s

      - name: Port forward & test
        run: |
          kubectl port-forward svc/devops-mini-service 5000:5000 &
          sleep 5
          curl -f http://127.0.0.1:5000








